### ISSUE TITLE
java: no such file or directory

### ISSUE THREAD

**Issue by adi1090x** [Hax4us/Tmux-Bunch#1]
Always get this error. in every version.
never get it made work for me.
Any Suggestions?

![s80312-092646](https://user-images.githubusercontent.com/26059688/37302978-12bd6a9e-2653-11e8-9cb2-ea80fd2b7102.jpg)

**Comment by lkdevil** [comment]
can you plz provide some info in the form of this :-
* Architecture : YOUR_ARCH
* Default Shell : DEFAULT_SHELL (for example bash zsh or any other )

**Comment by lkdevil** [comment]
I am also using this tool and thnx to @Hax4us .... its very useful

**Comment by adi1090x** [comment]
Arch: aarch64
Shell: zsh

**Comment by Hax4us** [comment]
Can you try with bash and give results

**Comment by adi1090x** [comment]
I guess, it's not a shell issue... It's path issue, as you can see, I'm using tmux-bunch on a different directory instead of home.
Well, I managed to make it work for me as I installed Java separately.
Just modified your tool according to my need.
Thanks anyway @Hax4us.

**Comment by Hax4us** [comment]
Wlcm :) I didn't notice your path and yes by default my tool will only work on HOME directory
