### ISSUE TITLE
missing a file

### ISSUE THREAD

**Issue by jxnTermux** [Hax4us/Tmux-Bunch#10]
[*] Please wait while binding.......🕜

WARNING: Nokogiri was built against LibXML version 2.9.7, but has dynamically loaded 2.9.8
Using APK template: google-now-launcher-1-3-large-en-android.apk
No platform was selected, choosing Msf::Module::Platform::Android from the payload
No Arch selected, selecting Arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
[*] Adding payload as package com.google.android.launcher.tshqn
[*] Loading /data/data/com.termux/files/usr/tmp/d20180611-7876-1bi6p9l/original/smali/com/google/android/launcher/StubApp.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Adding <uses-permission android:name="android.permission.SET_WALLPAPER"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.READ_SMS"/>
[*] Adding <uses-permission android:name="android.permission.CALL_PHONE"/>
[*] Adding <uses-permission android:name="android.permission.RECORD_AUDIO"/>
[*] Adding <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
[*] Adding <uses-permission android:name="android.permission.INTERNET"/>
[*] Adding <uses-permission android:name="android.permission.READ_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_SETTINGS"/>
[*] Adding <uses-permission android:name="android.permission.WAKE_LOCK"/>
[*] Adding <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.CHANGE_WIFI_STATE"/>
[*] Adding <uses-permission android:name="android.permission.RECORD_AUDIO"/>
[*] Adding <uses-permission android:name="android.permission.READ_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.SEND_SMS"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
[*] Adding <uses-permission android:name="android.permission.RECEIVE_SMS"/>
[*] Adding <uses-permission android:name="android.permission.CAMERA"/>
[*] Rebuilding google-now-launcher-1-3-large-en-android.apk with meterpreter injection as /data/data/com.termux/files/usr/tmp/d20180611-7876-1bi6p9l/output.apk and yes it's me guys...your friend Lokesh (devil) thanx for using my tool TMUX-BUNCH V-2.5
[*] Note :- Tmux-Bunch is my tool but this apk.rb script is written by Metasploit team and I am just a modifier of this script for binding payload in termux
Payload size: 5 bytes
[#<FileUtils::Entry_ /data/data/com.termux/files/usr/tmp/d20180611-7876-1bi6p9l/payload.apk>, #<FileUtils::Entry_ /data/data/com.termux/files/usr/tmp/d20180611-7876-1bi6p9l/original.apk>, #<FileUtils::Entry_ /data/data/com.termux/files/usr/tmp/d20180611-7876-1bi6p9l/original>, #<FileUtils::Entry_ /data/data/com.termux/files/usr/tmp/d20180611-7876-1bi6p9l/payload>, #<FileUtils::Entry_ /data/data/com.termux/files/usr/tmp/d20180611-7876-1bi6p9l/output.apk>]
 signing apk .......
/data/data/com.termux/files/home/Tmux-Bunch/.signapk: 9: /data/data/com.termux/files/home/Tmux-Bunch/.signapk: /data/data/com.termux/files/home/Tmux-Bunch/.bunch/openjdk/bin/java: not found

 We will met again :D , have a payload day..! 📢

 press ENTER for main menu

**Comment by akhilporandla21041998** [comment]
I'm getting an error while binding the payload to the fb_lite app
And the error is :
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
[*] Adding payload as package com.uc.browser.en.axajz
[*] Loading /data/data/com.termux/files/usr/tmp/d20180612-27587-u2lc01/original/smali/com/uc/browser/UCBrowser.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Adding <uses-permission android:name="android.permission.CALL_PHONE"/>
[*] Adding <uses-permission android:name="android.permission.RECEIVE_SMS"/>
[*] Adding <uses-permission android:name="android.permission.READ_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.RECORD_AUDIO"/>
[*] Adding <uses-permission android:name="android.permission.SEND_SMS"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
[*] Adding <uses-permission android:name="android.permission.READ_SMS"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.READ_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.RECORD_AUDIO"/>
[*] Rebuilding uc.apk with meterpreter injection as /data/data/com.termux/files/usr/tmp/d20180612-27587-u2lc01/output.apk and yes it's me guys...your friend Lokesh (devil) thanx for using my tool TMUX-BUNCH V-2.5
[*] Note :- Tmux-Bunch is my tool but this apk.rb script is written by Metasploit team and I am just a modifier of this script for binding payload in termux
Payload size: 5 bytes
[#<FileUtils::Entry_ /data/data/com.termux/files/usr/tmp/d20180612-27587-u2lc01/payload.apk>, #<FileUtils::Entry_ /data/data/com.termux/files/usr/tmp/d20180612-27587-u2lc01/original.apk>, #<FileUtils::Entry_ /data/data/com.termux/files/usr/tmp/d20180612-27587-u2lc01/original>, #<FileUtils::Entry_ /data/data/com.termux/files/usr/tmp/d20180612-27587-u2lc01/payload>, #<FileUtils::Entry_ /data/data/com.termux/files/usr/tmp/d20180612-27587-u2lc01/output.apk>]
 signing apk .......
/data/data/com.termux/files/home/Tmux-Bunch/.signapk: 9: /data/data/com.termux/files/home/Tmux-Bunch/.signapk: /data/data/com.termux/files/home/Tmux-Bunch/.bunch/openjdk/bin/java: not found

 We will met again :D , have a payload day..! 📢

 press ENTER for main menu
![screenshot_2018-06-12-08-56-11-782_com termux](https://user-images.githubusercontent.com/36566807/41269723-7cb3d5b4-6e24-11e8-9a7d-7c8f238f8299.png)

**Comment by akhilporandla21041998** [comment]
Please help me hax4us soon

**Comment by Hax4us** [comment]
Can you try new release 
Install again from this guide 
https://github.com/Hax4us/Tmux-Bunch/blob/master/README.md
And let me know that it is working or not

**Comment by akhilporandla21041998** [comment]
Not working again generating the different error

**Comment by Hax4us** [comment]
Without screenshot I can't help

**Comment by akhilporandla21041998** [comment]
Here is screenshot

**Comment by akhilporandla21041998** [comment]
![screenshot_2018-06-12-21-18-19-417_com termux](https://user-images.githubusercontent.com/36566807/41301792-8497c256-6e86-11e8-8845-e1ee9d008570.png)

**Comment by akhilporandla21041998** [comment]
Help me

**Comment by Hax4us** [comment]
What's your android version ? And are you sure that you are using latest version ? Bcz I can still see v2.5 in your screenshot

**Comment by akhilporandla21041998** [comment]
Ha yes
U sent a link of 2.6 I downloaded it and my android version is 7.1

**Comment by Hax4us** [comment]
Run tmuxbunch and give screenshot I want to see logo

**Comment by akhilporandla21041998** [comment]
In logo it is v2.6

**Comment by Hax4us** [comment]
Rerun setup script of Tmux-Bunch and give ss here

**Comment by akhilporandla21041998** [comment]
Yes I did

**Comment by akhilporandla21041998** [comment]
Help me sir

**Comment by Hax4us** [comment]
Delete apk.rb 
`rm $HOME/metasploit-framework/lib/msf/core/payload/apk.rb`

Manually download this by curl / wget / axel any other tool
 for ex I am using axel here
`axel https://github.com/Hax4us/Metasploit_termux/raw/master/apk.rb -o $HOME/metasploit-framework/lib/msf/core/payload/`
Then try again Tmux-Bunch

**Comment by akhilporandla21041998** [comment]
Brother again getting error same error

**Comment by akhilporandla21041998** [comment]
Please help me sir

**Comment by akhilporandla21041998** [comment]
Please solve this please

**Comment by Hax4us** [comment]
Screenshot of binding

**Comment by akhilporandla21041998** [comment]
This is screenshot

**Comment by akhilporandla21041998** [comment]
Bro
Have you solved my problem

**Comment by Hax4us** [comment]
![intex aqua trend_2018-06-13-22-55-50](https://user-images.githubusercontent.com/30441647/41367658-49912fb2-6f5d-11e8-872e-763caac2f53f.png)
![intex aqua trend_2018-06-13-22-57-02](https://user-images.githubusercontent.com/30441647/41367692-60a55d0e-6f5d-11e8-89f9-c7dbca245e49.png)
![intex aqua trend_2018-06-13-22-57-39](https://user-images.githubusercontent.com/30441647/41367702-6d98320c-6f5d-11e8-9f94-5bb6a9fac570.png)

I can't see any problem in my phone ..
I want to see the output of this command 
`grep "aapt" $HOME/metasploit-framework/lib/msf/core/payload/apk.rb`

**Comment by mithunpp4u** [comment]
Lokesh can u please help me with this snapshot..

**Comment by mithunpp4u** [comment]
![screenshot_2018-06-14-20-39-14](https://user-images.githubusercontent.com/40272102/41421326-31955084-7014-11e8-8d69-2a43f4cb151b.png)

**Comment by Hax4us** [comment]
Give output/screenshot of this command `termux-info` 
And also give your Original app in which you are trying to bind payload

**Comment by mithunpp4u** [comment]
This is the termux info

![screenshot_2018-06-14-21-01-22](https://user-images.githubusercontent.com/40272102/41422390-6fc9c3ba-7016-11e8-96c2-cb442720c513.png)

**Comment by mithunpp4u** [comment]
I tried ccleaner also but same issue

**Comment by akhilporandla21041998** [comment]
grep "aapt" $HOME/metasploit-framework/lib/msf/core/payload/apk.rb 
Output of the above command is nothing no erro
$ rgrep "aapt"$HOME/metasploit-framework/lib/msf/core/payload/apk.rb
$ 
This is the out put

**Comment by mithunpp4u** [comment]
Dear Lokesh... thank you...

i just updated the tmuxbunch , now its working....

but i dnt know y its showing 2.6 , when i m having above issue.

**Comment by akhilporandla21041998** [comment]
grep "aapt" $HOME/metasploit-framework/lib/msf/core/payload/apk.rb
Output of this command

**Comment by akhilporandla21041998** [comment]
Hello bro will u please tell me how to remove the add termux packages in my
termux package

**Comment by akhilporandla21041998** [comment]
Because I'm getting error while installing the packages

**Comment by akhilporandla21041998** [comment]
Lokesh sir I'm getting error in apktool please solve this

**Comment by akhilporandla21041998** [comment]
Lokesh sir please solve this iam getting error in apktool

**Comment by Hax4us** [comment]
@akhilporandla21041998  please don't spam here 
And I can't help without sufficient information I want these information in the form of screenshots

1) `cd && ls`
2) `ls metasploit-framework`
3) `grep "aapt" $HOME/metasploit-framework/lib/msf/core/payload/apk.rb`
4) `tmuxbunch`
5) `termux-info`

**Comment by akhilporandla21041998** [comment]
Please solve this I have uninstalled the tmuxbunch

**Comment by Hax4us** [comment]
@mithunpp4u said that Tmux-Bunch is working after update 
@akhilporandla21041998  I am closing this issue until you give sufficient information for debugging 
Feel free to open with required information

**Comment by akhilporandla21041998** [comment]
Please send the apktool for termux link bro

**Comment by akhilporandla21041998** [comment]
I gave na sufficient information

**Comment by akhilporandla21041998** [comment]
Sir the screenshots u asked na
