### ISSUE TITLE
java.io.file Not found

### ISSUE THREAD

**Issue by MITHUCHOWDHURY** [Hax4us/Tmux-Bunch#12]
![screenshot_20180615-203051](https://user-images.githubusercontent.com/40330358/41504954-634d9fca-721f-11e8-80de-62fadce9439d.png)
![screenshot_20180617-111004](https://user-images.githubusercontent.com/40330358/41504956-6cf39e6c-721f-11e8-95e7-3613e4c11dbf.png)

How to i solve this?

**Comment by Hax4us** [comment]
Can you give app (target apk) for testing ?

**Comment by MITHUCHOWDHURY** [comment]
Hlw r u there? I What'sapp you please check

**Comment by MITHUCHOWDHURY** [comment]
Is Aapt fixed?

**Comment by MITHUCHOWDHURY** [comment]
Hlw....

**Comment by MITHUCHOWDHURY** [comment]
R you there?

**Comment by MITHUCHOWDHURY** [comment]
![screenshot_20180618-182725](https://user-images.githubusercontent.com/40330358/41535760-53ffb54c-7325-11e8-99d1-81e28a3180da.png)

Is there any problem in my apktool?

**Comment by MITHUCHOWDHURY** [comment]
![screenshot_20180619-132600](https://user-images.githubusercontent.com/40330358/41582873-a077c6d6-73c4-11e8-943e-ac83d0b76795.png)

**Comment by LottaR17** [comment]
Helpme , java not installed

**Comment by MITHUCHOWDHURY** [comment]
bro please help
