### ISSUE TITLE
Error while signig apk plz help me

### ISSUE THREAD

**Issue by waleedalbash** [Hax4us/Tmux-Bunch#19]
![screenshot_2018-07-13-18-38-05](https://user-images.githubusercontent.com/41225717/42721458-0435b42a-8744-11e8-9302-c4a18e5739ce.png)
[*] Please wait while binding.......🕜

Using APK template: azar.apk
No platform was selected, choosing Msf::Module::Platform::Android from the payload
No Arch selected, selecting Arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
[*] Adding payload as package com.azarlive.android.ivrie
[*] Loading /data/data/com.termux/files/usr/tmp/d20180714-13618-1h3olag/original/smali/com/azarlive/android/AzarApplication.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Adding <uses-permission android:name="android.permission.RECEIVE_SMS"/>
[*] Adding <uses-permission android:name="android.permission.CHANGE_WIFI_STATE"/>
[*] Adding <uses-permission android:name="android.permission.SET_WALLPAPER"/>
[*] Adding <uses-permission android:name="android.permission.READ_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_SETTINGS"/>
[*] Adding <uses-permission android:name="android.permission.READ_SMS"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
[*] Adding <uses-permission android:name="android.permission.CALL_PHONE"/>
[*] Adding <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CALL_LOG"/>
[*] Rebuilding azar.apk with meterpreter injection as /data/data/com.termux/files/usr/tmp/d20180714-13618-1h3olag/output.apk and yes it's me guys...your friend Lokesh (Hax4Us) thanx for using my tool TMUX-BUNCH
[*] Note :- Tmux-Bunch is my tool but this apk.rb script is written by Metasploit team and I am just a modifier of this script for binding payload in termux
Payload size: 0 bytes

 signing apk .......
Aborted

**Comment by jumaris88** [comment]
Same here. I can't find the output apk.

**Comment by waleedalbash** [comment]
What we should do now

**Comment by Hax4us** [comment]
@waleedalbash which version of Tmux-Bunch you are using and also give output of this command `termux-info`

**Comment by waleedalbash** [comment]
![screenshot_2018-07-14-09-41-13](https://user-images.githubusercontent.com/41225717/42721858-79305c5c-874a-11e8-810f-e910dc2e4964.png)
Tmux-Bunch v2.7

**Comment by Hax4us** [comment]
Make sure you did not  Oreo variant and give screenshots after these steps

`apksigner -p hax4us keystore /path/to/anyapk.apk $HOME/anyapk.apk`
Then `ls $HOME`
__Dont forget to change `path/to/anyapk.apk` with real path to any app `

**Comment by waleedalbash** [comment]
![screenshot_2018-07-14-10-30-05](https://user-images.githubusercontent.com/41225717/42722215-e95136ea-8750-11e8-837b-fd8e78ff30a4.png)
Aborted

**Comment by Hax4us** [comment]
Now this `apt install strace -y && strace -o log.txt apksigner -p hax4us keystore  /sdcard/azar.apk $HOME/azar.apk`
It will create a file __log.txt__ in your home so you have to give me that file

**Comment by waleedalbash** [comment]
[log.txt](https://github.com/Hax4us/Tmux-Bunch/files/2194764/log.txt)

**Comment by waleedalbash** [comment]
I have pc and rooted phone but the screen is broken

**Comment by Hax4us** [comment]
Actually this error is related to apksigner and i cant give log of logcat because apksigner is working in my phone which is package of Termux so i opened an issue   https://github.com/termux/termux-packages/issues/2652 on behalf of you , please continue there thnx.

**Comment by Hax4us** [comment]
And for temporary solution u can use v2.6 instead of v2.7

**Comment by waleedalbash** [comment]
Man can u give me tmux-bunch 2.3 or older that can be work

**Comment by Hax4us** [comment]
@waleedalbash https://github.com/Hax4us/Tmux-Bunch/releases/download/2.6/Tmux-Bunch-2.6.tar.gz

**Comment by waleedalbash** [comment]
Do u have older i have another error with 2.6

**Comment by Hax4us** [comment]
What type of error ? Open new issue if u have

**Comment by waleedalbash** [comment]
Ok thanks

**Comment by djaman** [comment]
] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
Error: Unable to find hook point in /data/data/com.termux/files/usr/tmp/d20181230-28524-k7d0on/original/smali*/jaikalki/biomagzine/com/class10ncertmathhindi/MainActivity.smali
 signing apk .......
mv: cannot stat '/data/data/com.termux/files/home/Tmux-Bunch/unsign/output.apk': No such file or directory
Please Help
