### ISSUE TITLE
Bad system call while trying to decompile

### ISSUE THREAD

**Issue by slogar25** [Hax4us/Tmux-Bunch#21]
line 199: 31950 Bad system call         sh $dir/.apktool d $dir/decompiler/$OUTPUT -o $dir/recompiler/$OUTPUT

**Comment by Hax4us** [comment]
Which version u r using ? And also give output of `termux-info`

**Comment by slogar25** [comment]
I believe I'm using the latest v2.7 and output as follows:
termux-info
Updatable packages:
All packages up to date
System information:
Linux localhost 4.4.116-g5ec1df259c0f #1 SMP PREEMPT Wed Jun 6 17:47:07 UTC 2018 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
Google
Device model:
Pixel 2 XL

**Comment by Hax4us** [comment]
Can I see your Tmux-Bunch logo which will be appear after the command `tmuxbunch`

**Comment by Hax4us** [comment]
Give screenshots after this command
`apktool`

**Comment by slogar25** [comment]
Sorry this took so long
![screenshot_20180802-112117](https://user-images.githubusercontent.com/4675147/43593652-5db6d612-9646-11e8-981a-31f52da6632d.png)

**Comment by Hax4us** [comment]
Install Oreo version of tmuxbunch

**Comment by jamert92** [comment]
hi, i know that this is an old issue, but, now i have the same problem and can´t find a solution 
Android 9 
aarch64
Tmux-Bunch-2.7-oreo installed

i hope you can help me.
thanks in advance
