### ISSUE TITLE
Apktool not supported

### ISSUE THREAD

**Issue by dre88mz** [Hax4us/Tmux-Bunch#7]
Good day. I would like to ask for help. Every time im going to bind payload to apk it always says not supported apktool. What will be the work aroud for this. 
![screenshot_20180424-162653_termux](https://user-images.githubusercontent.com/37585602/39175207-424cff60-4799-11e8-8211-1c70c8b1db31.jpg)

**Comment by Hax4us** [comment]
Check if apktool is working or not .... Just execute this command `apktool `

**Comment by Hax4us** [comment]
Hmm.. Its very rare issue ... Maybe rom specific.. Well give output of `termux-info` command

**Comment by crazycheken** [comment]
I have too thiz problem bro.....!! Apk tool is not working.help me. 
and thanks for yur reply

**Comment by Hax4us** [comment]
@crazycheken give output of `termux-info`

**Comment by crazycheken** [comment]
Bro how to attach the photo in comment box.there is no option to attach

**Comment by Hax4us** [comment]
I think you are using github in mobile version so open in desktop mode or version

**Comment by Hax4us** [comment]
Can you try new release 2.5

**Comment by MITHUCHOWDHURY** [comment]
![screenshot_20180617-111004](https://user-images.githubusercontent.com/40330358/41504938-07ab249e-721f-11e8-94b7-4ccf4ea85c74.png)
Bro i think my apktool all ok. But app not binding. It's say java.io.file not found. Please help

**Comment by Hax4us** [comment]
Can you share screenshot of error and also give legit or original app in which you are trying to bind payload

**Comment by MITHUCHOWDHURY** [comment]
You can see my new issue
